# Generated by Django 3.0.6 on 2020-05-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=30)),
                ('creator_name', models.CharField(max_length=30)),
                ('likes', models.IntegerField()),
                ('onair', models.BooleanField()),
                ('subscriber', models.IntegerField()),
                ('link1', models.TextField()),
                ('link2', models.TextField()),
                ('link3', models.TextField()),
            ],
        ),
    ]
