# Generated by Django 2.0.13 on 2020-08-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
