# Generated by Django 3.0.7 on 2020-06-28 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='PHOTO_NAME')),
                ('about', models.TextField(default='ABOUT_PHOTO')),
                ('when', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('pic', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
    ]
