# Generated by Django 3.0.7 on 2020-06-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjgall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='about',
            field=models.TextField(blank=True, default='ABOUT_PHOTO'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.TextField(blank=True, default='PHOTO_NAME'),
        ),
    ]
